:rocket: Adiciona Q-Learning
turing-usp/Aprendizado-por-Reforco pull request #17
Opened 2020-08-30 17:42 UTC by arielguerreiro

Fiz uma primeira implementação de Q-Learning, usando o ambiente Taxi-V3

2020-08-30 19:45 UTC, nelsonayamashita commented on Aprendizado por Reforço Clássico/Q-Learning/Imagens/q-learning.svg
> +</svg>
Gente para mais alguém a imagem ficou assim?
![Screenshot_20200830_164333](https://user-images.githubusercontent.com/46365985/91668103-24407780-eae0-11ea-9672-ee620b077f39.png)
Talvez a gente esteja com um problema no Latex? Talvez seja um problema da minha máquina?

2020-08-30 19:47 UTC, arielguerreiro commented on Aprendizado por Reforço Clássico/Q-Learning/Imagens/q-learning.svg
> +</svg>
provavelmente foi do aplicativo de conversão de tex para svg que eu usei, vou usar o recomendado do @fernandokm

2020-08-30 23:09 UTC, arielguerreiro commented on Aprendizado por Reforço Clássico/Q-Learning/Imagens/q-learning.svg
> +</svg>
Imagem arrumada

2020-08-30 23:09 UTC, arielguerreiro commented
Imagem arrumada

2020-08-30 23:48 UTC, fernandokm requested changes
- Conforme discussão do PR #14, o nome da pasta "Imagens" deve ser alterado para "imgs".
- O arquivo "q-learning.tex" tá vazio.

2020-08-30 23:48 UTC, fernandokm commented on Aprendizado por Reforço Clássico/Q-Learning/README.md
> +A política adotada é a chamada ε-greedy (ε-guloso). Um número aleatório no intervalo entre 0 e 1 é comparado com ε. Se o número aleatório for menor do que o valor de ε, a ação tomada vai ser aleatóri
Talvez sejam bom explicitar que o agente vai tomar uma ação aleatória com probabilidade &epsilon;.

2020-08-31 11:50 UTC, arielguerreiro commented
Nome da pasta foi alterado e acrescentei a parte sobre a política

2020-09-03 13:17 UTC, Berbardo commented
Eu tinha dividido os algoritmos clássicos assim por enquanto:

![image](https://user-images.githubusercontent.com/48636340/92119723-91008e00-edce-11ea-985c-634b76689f27.png)

Só que a pasta do Q-Learning estaria fugindo dessa classificação:

![image](https://user-images.githubusercontent.com/48636340/92119811-ae355c80-edce-11ea-8337-5343463d19a5.png)

Aí se quiser a gente pode ou colocar dentro de uma pasta de TD ou mudar a divisão mesmo, depende do que vocês acharem

2020-09-03 13:20 UTC, Berbardo requested changes
Linkar Q-Learning no README de Algoritmos Clássicos.

Acho que seria legal explicar melhor o código no notebook tbm

2020-09-03 20:37 UTC, arielguerreiro commented
Acho que podemos criar uma pasta de TD e colocar Q-Learning dentro sim, vou arrumar o README e comentar o código no notebook

2020-09-03 20:48 UTC, dueiras commented
Em Algoritmos Classicos/Q-Learning/README, na parte de **Algoritmos**, o link para o pseudocódigo está quebrado

2020-09-03 20:51 UTC, dueiras requested changes

2020-09-03 20:51 UTC, dueiras commented on Aprendizado por Reforço Clássico/Q-Learning/README.md
> +![Algoritmo de Q-Learning](Imagens/q-learning.svg)
![Algoritmo de Q-Learning](imgs/q-learning.svg)

2020-09-03 20:52 UTC, dueiras requested changes

2020-09-03 20:52 UTC, dueiras commented on Aprendizado por Reforço Clássico/Q-Learning/README.md
> +![Algoritmo de Q-Learning](Imagens/q-learning.svg)
```suggestion
![Algoritmo de Q-Learning](imgs/q-learning.svg)
```

2020-09-03 23:16 UTC, fernandokm commented on Aprendizado por Reforço Clássico/Q-Learning/README.md
> +O algoritmo de Q-Learning é um dos algoritmos do grupo TD (Temporal difference, diferença temporal), que estimam a função de valor por meio de uma estimativa a partir de outra estimativa, processo ch
```suggestion
O algoritmo de Q-Learning é um dos algoritmos do grupo TD (Temporal difference, diferença temporal), que estimam a função de valor por meio de uma estimativa a partir de outra estimativa, processo chamado _bootstrapping_.
```
Acho que tá errado sem o -ing.

2020-09-03 23:16 UTC, fernandokm commented on Aprendizado por Reforço Clássico/Q-Learning/imgs/q-learning.tex
> +    Até S ser terminal
```suggestion
    $Q(s, a)$ arbitrário para todo $s$ e $a$, exceto para $Q (\mathrm{terminal}, \cdot) = 0$

Loop para cada episódio:
    Inicializar $S$
    Loop para cada passo do episódio:
        Escolher $A$ de $S$ usando política derivada de $Q$ (como $\varepsilon$-guloso)
        Tomar ação $A$, receber $R$, $S'$
        $Q(S, A) \leftarrow Q(S, A) + \alpha [R + \gamma \max_{a}Q(S', a) - Q(S, A)]$
        $S \leftarrow S'$
    Até $S$ ser terminal
```

2020-09-11 00:33 UTC, Berbardo commented
> Acho que podemos criar uma pasta de TD e colocar Q-Learning dentro sim, vou arrumar o README e comentar o código no notebook

@arielguerreiro ainda não foi resolvido

2020-10-01 21:41 UTC, fernandokm approved these changes

2020-10-02 18:28 UTC, Berbardo requested changes
![image](https://user-images.githubusercontent.com/48636340/94957219-c8dd1d00-04c3-11eb-8763-ea4dbcf29495.png)

Faltou excluir a pasta antiga.

![image](https://user-images.githubusercontent.com/48636340/94957275-db575680-04c3-11eb-8da9-cb87662ce366.png)

E seria legal colocar o link pra pasta de TD igual a gente fez pro Bandits e pro Monte Carlo

2021-01-18 21:44 UTC, FelipeAugustoMachado approved these changes

2021-01-18 21:44 UTC, FelipeAugustoMachado commented on Aprendizado por Reforço Clássico/TD/Q-Learning/Q-Learning.ipynb
> +    "Porém, os métodos TD tem uma vantagem sobre os métodos de Monte Carlo (MC), pois são capazes de aprendizado _online_, ou seja, aprendem com a passagem do episódio, enquanto os métodos de MC prec
Deixaria assim:

"**No entanto**, os métodos TD **têm** uma vantagem (...)"

2021-01-18 21:44 UTC, FelipeAugustoMachado commented on Aprendizado por Reforço Clássico/TD/Q-Learning/Q-Learning.ipynb
> +    "        #next_state = tuple(next_state)\n",
Eliminar essas duas linhas de comentários.

2021-01-18 21:44 UTC, FelipeAugustoMachado commented on Aprendizado por Reforço Clássico/TD/Q-Learning/Q-Learning.ipynb
> +    "        if state not in self.Q.keys(): #a\n",
Arrumar o comentário do if.

2021-01-18 21:44 UTC, FelipeAugustoMachado commented on Aprendizado por Reforço Clássico/TD/Q-Learning/Q-Learning.ipynb
> +    "       #next_state = discretize(env, next_state)\n",
Remover Comentário.

2021-01-18 21:44 UTC, FelipeAugustoMachado commented on Aprendizado por Reforço Clássico/TD/Q-Learning/README.md
> +Porém, os métodos TD tem uma vantagem sobre os métodos de Monte Carlo (MC), pois são capazes de aprendizado _online_, ou seja, aprendem com a passagem do episódio, enquanto os métodos de MC precisam
Mesmas modificações do notebook:
"**No entanto**, os métodos TD **têm** (...)"

2021-02-06 04:00 UTC, nelsonayamashita reviewed
Apenas um erro de imagem (como sempre 😞) no notebook que acredito que possa ser resolvido facilmente.

2021-02-25 11:24 UTC, arielguerreiro commented on Aprendizado por Reforço Clássico/TD/Q-Learning/Q-Learning.ipynb
> +    "Porém, os métodos TD tem uma vantagem sobre os métodos de Monte Carlo (MC), pois são capazes de aprendizado _online_, ou seja, aprendem com a passagem do episódio, enquanto os métodos de MC prec
Alterado

2021-02-25 11:27 UTC, arielguerreiro commented on Aprendizado por Reforço Clássico/TD/Q-Learning/Q-Learning.ipynb
> +    "        #next_state = tuple(next_state)\n",
Alterado

2021-02-25 11:28 UTC, arielguerreiro commented on Aprendizado por Reforço Clássico/TD/Q-Learning/Q-Learning.ipynb
> +    "        if state not in self.Q.keys(): #a\n",
Feito

2021-02-25 11:29 UTC, arielguerreiro commented on Aprendizado por Reforço Clássico/TD/Q-Learning/README.md
> +Porém, os métodos TD tem uma vantagem sobre os métodos de Monte Carlo (MC), pois são capazes de aprendizado _online_, ou seja, aprendem com a passagem do episódio, enquanto os métodos de MC precisam
Alterado

2021-02-25 11:29 UTC, arielguerreiro commented on Aprendizado por Reforço Clássico/TD/Q-Learning/Q-Learning.ipynb
> +    "       #next_state = discretize(env, next_state)\n",
Feito

2021-02-25 11:30 UTC, arielguerreiro commented on Aprendizado por Reforço Clássico/Temporal-Difference/Q-Learning/Q-Learning.ipynb
> +    "![funcao q](https://camo.githubusercontent.com/003498f344a099b4d34d45aa2bc0841e562fa01e/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f6769662e6c617465783f715f5c706928732c6129267370616365
Alterado

2021-02-25 14:33 UTC, fernandokm submitted a review, later dismissed

2021-02-25 19:56 UTC, Berbardo commented on Aprendizado por Reforço Clássico/Temporal-Difference/README.md
> + - [Q-Learning](Q-Learning)
A gente vai colocar alguma descrição aqui?

2021-02-25 20:07 UTC, Berbardo requested changes

2021-02-25 20:07 UTC, Berbardo commented on Aprendizado por Reforço Clássico/Temporal-Difference/Q-Learning/README.md
> +No entanto, os métodos TD têm uma vantagem sobre os métodos de Monte Carlo (MC), pois são capazes de aprendizado _online_, ou seja, aprendem com a passagem do episódio, enquanto os métodos de MC prec
Aqui é _ações contínuas_ mesmo?

2021-02-25 20:07 UTC, Berbardo commented on Aprendizado por Reforço Clássico/Temporal-Difference/Q-Learning/README.md
> +O algoritmo de Q-Learning é extremamente versátil dentro dos métodos TD, por ser um algoritmo _off-policy_, ou seja, seu aprendizado não depende da política que está sendo seguida, diferente de outro
Não entendi muito bem o "Com isso, o treinamento é acelerado, pois só depende que os pares estado-ação sejam visitados."

2021-02-25 20:07 UTC, Berbardo commented on Aprendizado por Reforço Clássico/Temporal-Difference/Q-Learning/README.md
> +De forma resumida, o valor Q(S,A) é atualizado fazendo uma "correção" com "taxa de aprendizado" &alpha;, considerando a recompensa R recebida com a escolha da ação e a ação futura que maximiza o valo
Aqui acho que faz sentido comentar que o _R + γ*max Q'(S,a)_ é o nosso target, e o Q(S, A) a nossa estimativa, o que faz com que aquela expressão multiplicando o α seja o TD-error.

2021-02-25 20:07 UTC, Berbardo commented on Aprendizado por Reforço Clássico/Temporal-Difference/Q-Learning/Q-Learning.ipynb
> +  }
Que tal um graficozinho do retorno aqui?

2021-04-22 21:35 UTC, arielguerreiro commented on Aprendizado por Reforço Clássico/Temporal-Difference/Q-Learning/Q-Learning.ipynb
> +  }
Não

2021-06-12 04:30 UTC, arielguerreiro commented on Aprendizado por Reforço Clássico/Temporal-Difference/Q-Learning/README.md
> +O algoritmo de Q-Learning é extremamente versátil dentro dos métodos TD, por ser um algoritmo _off-policy_, ou seja, seu aprendizado não depende da política que está sendo seguida, diferente de outro
Alterado

2021-06-12 04:30 UTC, arielguerreiro commented on Aprendizado por Reforço Clássico/Temporal-Difference/Q-Learning/Q-Learning.ipynb
> +  }
No processo

2021-06-12 19:10 UTC, Berbardo commented on Aprendizado por Reforço Clássico/Temporal-Difference/Q-Learning/README.md
> +O algoritmo de Q-Learning é extremamente versátil dentro dos métodos TD, por ser um algoritmo _off-policy_, ou seja, seu aprendizado não depende da política que está sendo seguida, diferente de outro
Gostei

2021-06-12 19:13 UTC, Berbardo requested changes
Por mim tá check, só fazer passar as mudanças que você fez hoje no README pro notebook também, que não ficou atualizado.

2021-06-13 23:49 UTC, Berbardo approved these changes

2021-06-13 23:49 UTC, merged