Policy Gradient
turing-usp/Aprendizado-por-Reforco pull request #30
Opened 2020-11-06 22:29 UTC by fernandokm

Antes de eu criar o markdown com a explicação (que tá no notebook por enquanto), queria saber o que vocês acham da matemática que tá lá. Tava pensando em tirar aquilo e citar as fontes (paper/spinning up) que têm derivações do teorema de PG. Basicamente, eu tiraria as seções "A prob. de uma trajetória", "O gradiente de J" e "Demonstração do teorema de PG" e deixaria o foco na parte conceitual e de aplicação.

2020-11-07 20:31 UTC, Berbardo reviewed
Acho que vale a pena focar na parte conceitual e na prática mesmo, mas dá também pra colocar as derivações de PG em um apêndice no final do notebook e do README ou algo assim, aí dá pra colocar as fontes junto da explicação já em português.

Também tenho uma outra dúvida, a gente coloca o código já com baselines de uma vez? Nós podemos já colocar ele direto, colocar ele depois do código sem baselines ou separar em duas pastas dentro de PG também, não sei qual vocês preferem.

2020-11-12 23:53 UTC, fernandokm commented
Eu já deixaria junto, mas se preferirem separar depois é rápido de fazer

2020-11-20 21:30 UTC, Berbardo requested changes

2020-11-20 21:30 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Policy Gradient/PG.ipynb
> +    "\\end{align*}\n",
Aqui ele fica zoado no github

![image](https://user-images.githubusercontent.com/48636340/99851755-62d55380-2b5e-11eb-98c0-815155e2ccc8.png)

2020-11-22 17:33 UTC, nelsonayamashita reviewed
Parece tudo certo, principalmente no notebook.
O único problema é que para mim, no github, algumas imagens das fórmulas parecem com o link quebrado(?). Isso tbm está acontecendo para vcs ou só aqui?

2020-11-22 17:33 UTC, nelsonayamashita commented on Aprendizado por Reforço Profundo/Policy Gradient/README.md
> +Algo que será bem útil é o cálculo da probabilidade de uma trajetória <img src="https://latex.codecogs.com/svg.latex?\tau&space;=&space;(s_0,a_0,s_1,a_1,\dots)" title="\tau = (s_0,a_0,s_1,a_1,\dots)"
Aqui o link da equação parece quebrado para mim. Pra vcs tbm tá assim ou é só pra mim?

2020-11-22 17:33 UTC, nelsonayamashita commented on Aprendizado por Reforço Profundo/Policy Gradient/README.md
> +<img src="https://latex.codecogs.com/svg.latex?\begin{align*}&space;\log&space;p(\tau|\theta)&space;&=&space;\log&space;\mu(s_0)&space;&plus;&space;\log\pi(a_0|s_0,\theta)&space;&plus;&space;\log&spa
Aqui tbm apareceu quebrado.

2020-11-23 23:36 UTC, Berbardo submitted a review, later dismissed

2021-01-18 21:35 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Policy Gradient/README.md
> +###### (Se alguma equação neste README estiver com o link quebrado, você pode checar as equações corretas também no [notebook](PG.ipynb)!)
Vale a pena deixar essa mensagem aqui, visto que isso é um problema geral do github?

2021-01-18 21:56 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Policy Gradient/README.md
> +###### (Se alguma equação neste README estiver com o link quebrado, você pode checar as equações corretas também no [notebook](PG.ipynb)!)
Eu acho que vale só pra pessoa não vazar quando ver as equações quebradas

2021-04-22 22:00 UTC, rafael-acoelho requested changes

2021-05-06 17:07 UTC, FelipeAugustoMachado commented on Aprendizado por Reforço Profundo/Policy Gradient/PG.ipynb
> +    "No caso de DQN, nós estimávamos a qualidade de uma ação usando bootstrap e minizávamos o erro entre o agente e esse $Q_{\\mathrm{bootstrap}}$. Em PG, a situação é um pouco diferente, porque não
O "pi bootstrap" parece desalinhado no notebook

2021-05-06 17:14 UTC, FelipeAugustoMachado commented on Aprendizado por Reforço Profundo/Policy Gradient/PG.ipynb
> +    "![Baseline](imgs/baseline.svg)"
Talvez seja interessante colocar mais um parágrafo falando sobre o impacto dessa diferença, que tende a melhorar e talz.

2021-05-06 17:14 UTC, FelipeAugustoMachado commented on Aprendizado por Reforço Profundo/Policy Gradient/PG.ipynb
> +    "class PGBuffer:\n",
Colocar um comentário sobre o que é essa classe, para dar uma relembrada pro pessoal.

2021-05-06 17:14 UTC, FelipeAugustoMachado commented on Aprendizado por Reforço Profundo/Policy Gradient/PG.ipynb
> +    "## O gradiente de $J$\n",
Esse "J" está parecendo o retorno dos meus algoritmos de RL: tá pequeno.

2021-05-06 18:50 UTC, luish18 approved these changes

2021-06-19 00:16 UTC, Berbardo approved these changes

2021-06-19 19:23 UTC, Berbardo commented
@all-contributors please add @FelipeAugustoMachado for review

2021-06-19 19:23 UTC, Berbardo commented
@all-contributors please add @rafael-acoelho for review

2021-06-19 19:25 UTC, Berbardo commented
@all-contributors please add @rafael-acoelho for review

2021-06-19 20:00 UTC, merged