:sparkles: Acrescenta notebook de A2C
turing-usp/Aprendizado-por-Reforco pull request #32
Opened 2020-11-19 20:48 UTC by arielguerreiro

2020-11-26 19:15 UTC, Berbardo requested changes

2020-11-26 19:15 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Actor-Critic/A2C/A2C.ipynb
> +        "![pseudocode](https://i.postimg.cc/w38KTJQb/A2C-v6.png)\n",
### Algoritmo

#### Parâmetros

Acho que a parte de parâmetros podia estar mais parecida com o que o Ariel fez pra DDPG

![image](https://user-images.githubusercontent.com/48636340/100385519-9baf7580-3001-11eb-9274-0dc4bad5ecc1.png)

O _s_ não é um parâmetro e acho que dava pra dar uma explicada de onde vieram o 𝜃 e o 𝜔.

#### Ação

A ação a' aqui tem que estar entre $$.

![image](https://user-images.githubusercontent.com/48636340/100385624-ee892d00-3001-11eb-89ff-b05935a9af68.png)

#### Valor

Aqui não são os dois Vs que dependem do parâmetro 𝜔? Acho que faz mais sentido eles ficarem com o 𝜔 embaixo.

![image](https://user-images.githubusercontent.com/48636340/100385670-18425400-3002-11eb-9b7f-c937b7ec7f89.png)

2020-11-26 19:15 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Actor-Critic/A2C/A2C.ipynb
> +        "  - Mais lento\n",
Vamos manter essa parte no repo?

2020-11-26 19:15 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Actor-Critic/A2C/A2C.ipynb
> +        "##  Rede Dividida"
Acho que depois é melhor eu colocar alguma teoria aqui

2021-05-06 15:53 UTC, fernandokm submitted a review, later dismissed
Outras coisas que tão faltando:
- [ ] Adicionar gráficos
- [ ] Só pra deixar registrado, ainda precisamos criar/atualizar os READMEs em:
  - [ ] Aprendizado por Reforço Profundo
  - [ ] Aprendizado por Reforço Profundo/Actor Critic
  - [ ] Aprendizado por Reforço Profundo/Actor Critic/A2C

Quando tiver tudo certo, eu posso dar uma olhada nas fórmulas pra ver se tem alguma coisa de formatação pra melhorar.

2021-05-06 15:53 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Actor-Critic/A2C/A2C.ipynb
> +        "$$\\nabla_\\theta J(\\theta) =  \\mathbb{E}_{\\pi_\\theta} [\\nabla_\\theta log \\pi_\\theta(s,a)\\ \\delta]\\ \\ \\ \\text{TD Actor-Critic}$$\n",
Precisa arrumar isso. Tá renderizando errado no github, mas eu acho que é culpa do github.

2021-05-06 17:56 UTC, FelipeAugustoMachado commented on Aprendizado por Reforço Profundo/Actor-Critic/A2C/A2C.ipynb
> +        "$$A(s,a) = r + \\gamma V(s') - V(s)$$\n",
Seria legal comparar com o TD error, já que tá na figura

2021-05-06 18:00 UTC, FelipeAugustoMachado submitted a review, later dismissed

2021-06-06 01:21 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Actor-Critic/A2C/A2C.ipynb
> +        "$$\\nabla_\\theta J(\\theta) =  \\mathbb{E}_{\\pi_\\theta} [\\nabla_\\theta log \\pi_\\theta(s,a)\\ \\delta]\\ \\ \\ \\text{TD Actor-Critic}$$\n",
Não sei bem qual era o erro

2021-06-06 01:21 UTC, Berbardo commented
> Outras coisas que tão faltando:
> 
> * [ ]  Adicionar gráficos
> * [ ]  Só pra deixar registrado, ainda precisamos criar/atualizar os READMEs em:
>   
>   * [ ]  Aprendizado por Reforço Profundo
>   * [ ]  Aprendizado por Reforço Profundo/Actor Critic
>   * [ ]  Aprendizado por Reforço Profundo/Actor Critic/A2C
> 
> Quando tiver tudo certo, eu posso dar uma olhada nas fórmulas pra ver se tem alguma coisa de formatação pra melhorar.

Acho que já fiz tudo

2021-06-06 01:22 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Actor-Critic/A2C/A2C.ipynb
> +        "  - Mais lento\n",
O que acha @fernandokm? Você fez uma apresentação maior sobre o assunto que talvez desse pra colocar separado no repo.

2021-06-12 01:03 UTC, nelsonayamashita reviewed
Acho que só tem um erro no texto. Importante lembrar de modificar ele tanto no notebook quanto no readme.

2021-06-12 01:22 UTC, Berbardo commented on Aprendizado por Reforço Profundo/Actor-Critic/A2C/A2C.ipynb
> +        "$$A(s,a) = r + \\gamma V(s') - V(s)$$\n",
Cheguei a fazer, ficou bom?

2021-06-12 01:44 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Actor-Critic/A2C/A2C.ipynb
> +        "  - Mais lento\n",
Vamos tirar, e eu coloco minha apresentação no rep, conforme #35

2021-06-12 01:46 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Actor-Critic/A2C/A2C.ipynb
> +        "$$\\nabla_\\theta J(\\theta) =  \\mathbb{E}_{\\pi_\\theta} [\\nabla_\\theta log \\pi_\\theta(s,a)\\ \\delta]\\ \\ \\ \\text{TD Actor-Critic}$$\n",
O erro é que o código tem 4 fórmulas, mas o github só tá renderizando uma. Mas isso deve ser problema do github, então não sei o que fazer.

> ![image](https://user-images.githubusercontent.com/12588556/121761533-db622880-cb1f-11eb-8cbe-43dc819d2417.png)

2021-06-12 01:47 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Actor-Critic/A2C/A2C.ipynb
> +        "$$A(s,a) = r + \\gamma V(s') - V(s)$$\n",
Achei bom

2021-06-12 02:24 UTC, Berbardo approved these changes

2021-06-12 14:09 UTC, merged