On-Policy x Off-Policy
turing-usp/Aprendizado-por-Reforco pull request #36
Opened 2021-06-12 01:54 UTC by nelsonayamashita

2021-06-12 02:09 UTC, fernandokm requested changes
TODO (@fernandokm):
- [x] Texto duplicado nos slides 10 e 11
- [ ] Adicionar um slide explicitando as diferenças entre on-policy e off-policy
- [ ] Questões estéticas:
  - [ ] Arrumar o esquema de cores
  - [ ] Melhorar a capa (logo do turing, ...)
- [ ] Atualizar o pdf com todas as alterações acima

2021-06-19 10:53 UTC, FelipeAugustoMachado commented on Introdução/On-Policy x Off-Policy/README.md
> +  Esses dois termos são comumente utilizados em aprendizado por reforço para descrever diferentes tipos de  coleta e treinamento de dados em modelos desse tipo. Na [apresentação](On-Policy%20x%20Off-
"diferentes tipos de coleta e treinamento de dados em modelos desse tipo." não gostei muito dessa frase.

Eu substituiria por algo do tipo "duas diferentes estruturas de modelo, onde a experiência adquirida ao interagir com o ambiente é tratada de forma diferente, resultando em processos de treinamento distintos."

2021-06-19 10:54 UTC, FelipeAugustoMachado submitted a review, later dismissed

2021-06-19 20:03 UTC, Berbardo commented
Daria pra linkar essa pasta de On-Policy x Off-Policy em outros lugares do repo pra não ficar perdido

2021-06-24 22:33 UTC, nelsonayamashita commented
Gente, acho que  eu criei esse branch antes de algum merge e não tá com o A2C pra linkar. Depois de dar merge aqui eu linko lá.

2021-06-24 22:37 UTC, Berbardo approved these changes

2021-06-24 22:40 UTC, merged