Final texts
turing-usp/Aprendizado-por-Reforco pull request #41
Opened 2021-06-25 00:58 UTC by nelsonayamashita

Adicionei um textinho para TD.

Além disso adicionei links para os slides de On-Policy vs Off-Policy nos readmes de:
 - Q-Learning
 - PG
 - A2C

2021-06-25 01:05 UTC, Berbardo submitted a review, later dismissed
Copia e cola a explicação de TD-Learning [pra cá](https://github.com/turing-usp/Aprendizado-por-Reforco/tree/final-txts/Aprendizado%20por%20Refor%C3%A7o%20Cl%C3%A1ssico/Temporal-Difference) tb

2021-06-25 02:38 UTC, fernandokm requested changes

2021-06-25 02:38 UTC, fernandokm commented on Aprendizado por Reforço Clássico/Temporal-Difference/Q-Learning/README.md
> +O algoritmo de Q-Learning é extremamente versátil dentro dos métodos TD, por ser um algoritmo _off-policy_, ou seja, seu aprendizado não depende da política que está sendo seguida, diferente de outro
```suggestion
O algoritmo de Q-Learning é extremamente versátil dentro dos métodos TD, por ser um algoritmo _off-policy_, ou seja, seu aprendizado não depende da política que está sendo seguida, diferente de outros métodos TD, como SARSA. Com isso, o treinamento é mais eficiente, pois pode usar experiências armazenadas em seu treinamento, não somente o que o agente está observando no episódio em si. Você pode ler mais sobre a diferença entre algoritmos *On-Policy* e *Off-Policy* [aqui](https://github.com/turing-usp/Aprendizado-por-Reforco/tree/master/Introdu%C3%A7%C3%A3o/On-Policy%20x%20Off-Policy)
```

2021-06-25 02:38 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Actor-Critic/A2C/README.md
> +Como vimos na aula de [Policy Gradients](https://github.com/turing-usp/Aprendizado-por-Reforco/tree/master/Aprendizado%20por%20Refor%C3%A7o%20Profundo/Policy%20Gradient), existem algoritmos capazes d
Faria sentido tirar a terminologia de "aula", "hoje vamos ...", etc. do texto? Ou esses notebooks são aulas mesmo? (não sei se já discutimos isso na PR de A2C, e nem sei se cabe essa discussão nessa PR, mas fiquei dúvida em relação a isso)

2021-06-25 02:38 UTC, fernandokm commented on Aprendizado por Reforço Clássico/Temporal-Difference/README.md
> +Métodos de **Temporal-Difference** são algoritmos de Aprendizado por Reforço que aprendem utilizando principalmente técnicas de *bootstrapping* (uma estimativa a base de amostragem) da sua função de
Acho que o texto fica melhor assim. Talvez dê pra melhorar um pouco mais, mas não sei como.

Obs: se for aceitar a sugestão, lembrar de copiar pro README de RL clássico.

```suggestion
Métodos de **Temporal-Difference** são algoritmos de Aprendizado por Reforço que aprendem utilizando principalmente técnicas de *bootstrapping* (uma estimativa a base de amostragem) da sua função de valor. Esses métodos amostram do ambiente, assim como métodos de Monte Carlo, mas fazem atualizações com base em estimativas intermediárias. Ou seja, enquanto métodos de Monte Carlo atualizam as suas predições apenas no fim do episódio (quando todos os retornos já são conhecidos), métodos de  **Temporal-Difference** atualizam as suas predições a cada instante de tempo, utilizando *bootstrapping* para estimar o retorno do episódio.
```

2021-06-25 02:44 UTC, fernandokm requested changes

2021-06-25 02:44 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Actor-Critic/A2C/README.md
> +Importante notar que A2C, assim como Policy Gradient, é um algoritmo **On-Policy**. Você pode ler mais sobre a diferença entre algoritmos **On-Policy vs. Off-Policy** [aqui](https://github.com/turing
Mesma sugestão feita no começo desse README.
```suggestion
Importante notar que A2C, assim como Policy Gradient, é um algoritmo **On-Policy**. Você pode ler mais sobre a diferença entre algoritmos **On-Policy vs. Off-Policy** [aqui](Introdu%C3%A7%C3%A3o/On-Policy%20x%20Off-Policy)
```

2021-06-25 02:44 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Policy Gradient/README.md
> +É importante notar que **Policy Gradient** é um algoritmo **On-Policy**. Você pode ler mais sobre a diferença entre algoritmos **On-Policy vs. Off-Policy** [aqui](https://github.com/turing-usp/Aprend
Mesma sugestão feita no começo do README de A2C.
```suggestion
É importante notar que **Policy Gradient** é um algoritmo **On-Policy**. Você pode ler mais sobre a diferença entre algoritmos **On-Policy vs. Off-Policy** [aqui](Introdu%C3%A7%C3%A3o/On-Policy%20x%20Off-Policy) 
```

2021-06-26 20:15 UTC, fernandokm requested changes
Última sugestão. Corrigi isso em um dos arquivos, mas esqueci dos outros.

2021-06-26 20:15 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Actor-Critic/A2C/README.md
> +Importante notar que A2C, assim como Policy Gradient, é um algoritmo **On-Policy**. Você pode ler mais sobre a diferença entre algoritmos **On-Policy vs. Off-Policy** [aqui](Introdu%C3%A7%C3%A3o/On-P
```suggestion
Importante notar que A2C, assim como Policy Gradient, é um algoritmo **On-Policy**. Você pode ler mais sobre a diferença entre algoritmos **On-Policy e Off-Policy** [aqui](Introdu%C3%A7%C3%A3o/On-Policy%20x%20Off-Policy)
```

2021-06-26 20:15 UTC, fernandokm commented on Aprendizado por Reforço Profundo/Policy Gradient/README.md
> +É importante notar que **Policy Gradient** é um algoritmo **On-Policy**. Você pode ler mais sobre a diferença entre algoritmos **On-Policy vs. Off-Policy** [aqui](Introdu%C3%A7%C3%A3o/On-Policy%20x%2
```suggestion
É importante notar que **Policy Gradient** é um algoritmo **On-Policy**. Você pode ler mais sobre a diferença entre algoritmos **On-Policy e Off-Policy** [aqui](Introdu%C3%A7%C3%A3o/On-Policy%20x%20Off-Policy) 
```

2021-06-28 10:44 UTC, fernandokm approved these changes

2021-06-29 23:57 UTC, merged