✨ Adiciona Guia de Aprendizado
turing-usp/Aprendizado-por-Reforco pull request #48
Opened 2022-02-17 21:15 UTC by Berbardo

2022-02-21 05:15 UTC, luish18 submitted a review, later dismissed
Gostei bastante da estrutura. Não tenho nada a adicionar

2022-02-21 10:36 UTC, fernandokm requested changes
Tô marcando como "Request changes" pq ainda falta fazer a taxonomia.

2022-02-21 10:36 UTC, fernandokm commented on Guia/README.md
> +  - Um importante algoritmo de Aprendizado por Reforço profundo que aproxima diretamente a política ótima, sem estimar função de valor.
```suggestion
  - Um importante algoritmo de Aprendizado por Reforço profundo que aproxima diretamente a política ótima, sem estimar a função de valor.
```

2022-02-22 02:57 UTC, Berbardo commented on README.md
> +## - [🗺️ Guia de Aprendizado](Guia)
eu botei porque tenho mais costume de linkar pasta mesmo

2022-02-24 10:03 UTC, fernandokm submitted a review, later dismissed

2022-02-24 21:25 UTC, nelsonayamashita commented
Acho que pode ser legal colocar uma recomendação de matérias de estudo. Algumas sugestões:
 - [Livro do Sutton & Barto](http://incompleteideas.net/book/RLbook2020.pdf)
 - [Site do Spinning up](https://spinningup.openai.com/en/latest/)
 - [Curso da Abelrta](https://www.coursera.org/specializations/reinforcement-learning) 
 - [Vídeo Aulas do David Silver](https://www.youtube.com/watch?v=2pWv7GOvuf0&list=PLzuuYNsE1EZAXYR4FJ75jcJseBmo4KQ9-)
 
Outras sugestões podem ser legais tbm.

2022-02-25 12:57 UTC, fernandokm approved these changes

2022-02-25 13:37 UTC, fernandokm requested changes

2022-02-25 13:37 UTC, fernandokm commented on Guia/README.md
> +A seguir, disponibilizamos também alguns materiais extra para aprofundas em mais conteúdos de Aprendizado por Reforço!
```suggestion
A seguir, disponibilizamos também alguns materiais extras para aprofundar em mais conteúdos de Aprendizado por Reforço!
```

2022-02-25 13:37 UTC, fernandokm commented on Guia/README.md
> +A seguir, disponibilizamos também alguns materiais extra para aprofundas em mais conteúdos de Aprendizado por Reforço!
Outra coisa, a regência/usod do verbo aprofundar ta correta ai?

2022-02-25 13:46 UTC, Berbardo commented on Guia/README.md
> +A seguir, disponibilizamos também alguns materiais extra para aprofundas em mais conteúdos de Aprendizado por Reforço!
atualizei a regencia do verbo aprofundar

2022-02-25 13:53 UTC, fernandokm approved these changes

2022-02-25 23:31 UTC, merged